version: '3'
services:

  python:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: python:3.8-buster
    ports:
      - "7500:7500"
    container_name: feminicidioAvista_container
    stdin_open: true
    restart: unless-stopped
    volumes: [ ~/python/data:/data/feminicidio ]
    links:
      - db
    networks:
      - backend

  db:
    image: paulafortuna/mongo-feminicidio
    ports:
      - "27017:27017"
    container_name: db
    volumes: [ ~/mongo/data:/data/db ]
    networks:
      - backend

networks:
  backend:
    driver: bridge



