version: '3'
services:

  python:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: feminicidioAvista_container
    image: paulafortuna/ubuntu-python-feminicidio
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: feminicidioAvistadb
      MONGODB_USERNAME: pythonuser
      MONGODB_PASSWORD: this_is_the_pass
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: paulafortuna/mongo-feminicidio
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: feminicidioAvistadb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
